### ISSUE TITLE
What is the recommended workflow for reading data?

### ISSUE THREAD

**Issue by ljschumacher** [WT215/bayNormJL.jl#1]
Thanks for providing this Julia package. I'm struggling with the lack of documentation. What is the recommended way to feed in data? For example, if I have a SingleCellExperiment object in an .rds file, is there a way to read this into Julia or should I convert it into something else in R first, and if so what?

**Comment by WT215** [comment]
Hello,

Thanks for trying bayNorm in Julia. Since you already have .rds, I recommend to directly work in R, use [bayNorm in R](https://bioconductor.org/packages/release/bioc/html/bayNorm.html).

In Julia, there seems to be no package like Seurat in R or Scanpy in Python. However, there are ways to convert R or Python object in Julia, but only for basic types like array but not SingleCellExperiment object. You can extract the data matrix from that object, and make it csv then load to Julia, but to complicated.

Hence, overall the convenient way is to work in R and use R version's bayNorm.

Hope these help.

**Comment by ljschumacher** [comment]
Thanks, I want to use Julia as I have downstream analysis using Julia packages. It sounds like I will have to save a matrix in R into a csv and read this into Julia.

Linus

**Comment by WT215** [comment]
Or you can extract matrix from SingleCellExperiment object, save it as .rds or spase matrix .mtx, then converted that in Julia. CSV will be too big.
